import type { CourseAttendanceStrategy, CourseResolution } from "@/types/game";

const COURSE_RULES: Record<CourseAttendanceStrategy, CourseResolution> = {
  serious: {
    strategy: "serious",
    attendanceCounted: true,
    directRollCallPenalty: 0,
    rollCallRiskDelta: 0,
    usualScoreRiskDelta: 0,
    proxyCost: 0,
    remedyPressure: 0,
    academicRiskDelta: -3,
    academicGain: 5,
    moodDelta: -1,
    stressDelta: 2,
    note: "认真上课，课堂收益最稳定，也能压低后续风险。",
  },
  mixed: {
    strategy: "mixed",
    attendanceCounted: true,
    directRollCallPenalty: 0,
    rollCallRiskDelta: 1,
    usualScoreRiskDelta: 1,
    proxyCost: 0,
    remedyPressure: 1,
    academicRiskDelta: 1,
    academicGain: 3,
    moodDelta: 0,
    stressDelta: 1,
    note: "正常跟课，推进平稳，但仍会留下少量平时分压力。",
  },
  skip_sometimes: {
    strategy: "skip_sometimes",
    attendanceCounted: false,
    directRollCallPenalty: 0,
    rollCallRiskDelta: 4,
    usualScoreRiskDelta: 3,
    proxyCost: 0,
    remedyPressure: 2,
    academicRiskDelta: 9,
    academicGain: 1,
    moodDelta: 1,
    stressDelta: -1,
    note: "偶尔翘课不会立刻扣学业值，但会抬高点名和平时分风险。",
  },
  skip_often: {
    strategy: "skip_often",
    attendanceCounted: false,
    directRollCallPenalty: 0,
    rollCallRiskDelta: 8,
    usualScoreRiskDelta: 6,
    proxyCost: 0,
    remedyPressure: 4,
    academicRiskDelta: 18,
    academicGain: 0,
    moodDelta: 2,
    stressDelta: -2,
    note: "经常翘课会把点名、平时分和补救成本一起推高，期末很容易爆雷。",
  },
  proxy: {
    strategy: "proxy",
    attendanceCounted: true,
    directRollCallPenalty: 0,
    rollCallRiskDelta: 2,
    usualScoreRiskDelta: 5,
    proxyCost: 120,
    remedyPressure: 3,
    academicRiskDelta: 10,
    academicGain: 1,
    moodDelta: 0,
    stressDelta: 1,
    note: "代签到能暂时躲过点名，但要花钱，也会提高平时分和后续补救成本。",
  },
  phone: {
    strategy: "phone",
    attendanceCounted: true,
    directRollCallPenalty: 0,
    rollCallRiskDelta: 1,
    usualScoreRiskDelta: 3,
    proxyCost: 0,
    remedyPressure: 2,
    academicRiskDelta: 6,
    academicGain: 2,
    moodDelta: 0,
    stressDelta: 0,
    note: "人到但心不在，通常不会立刻吃点名惩罚，但平时分和信息损失会慢慢累积。",
  },
};

export function resolveCourseStrategy(strategy: CourseAttendanceStrategy): CourseResolution {
  return COURSE_RULES[strategy];
}
